### ISSUE TITLE
dynamic dictionary validation

### ISSUE THREAD

**Issue by keith6014** [marshmallow-code/marshmallow#1347]
Say, I have a dictionary like this
```code json
{
  "title": "arba",
  "srv": {
    "A": [
      {
        "server:export0": "/mp1",
        "server:export1": "/mp2"
      }
    ],
    "B": [
      {
        "server:export1": "/mnt/ffee"
      }
    ]
  }
}
```
* "title" is mandatory. Must be string
* "srv" will be dynamic. Must be a string. Dynamic means, it will be called "srv", "foo","bar", or whatever
* "A" & "B" will be dynamic. Must be string

```python
class HostSchema(Schema):
    host = fields.Str()

class MainSchema(Schema):
    title = fields.Str()
    data = fields.NestedDict(HostSchema,key='name')

result = MainSchema().load(d)
```

**Comment by sloria** [comment]
See https://stackoverflow.com/questions/57437960/serializing-data-with-marshmallow-if-data-key-is-unknown/57470868#57470868 . You can use `from_dict` to build your schema completely dynamically.

**Comment by keith6014** [comment]
Thanks.

I am doing something like this
```python

class HostSchema(Schema):
    host = fields.Str()

class Schema(BaseSchema):
    @classmethod
    def from_dict(cls, fields_dict):
        attrs = fields_dict.copy()
        attrs["Meta"] = type(
                "GeneratedMeta", (getattr(cls, "Meta", object),), {"register": False}
                )
        return type("", (cls,), attrs)

MySchema = Schema.from_dict({
    "title" : fields.Str(),
    "unknown_key": fields.Dict(keys=fields.Str(),values=fields.List(fields.Nested(HostSchema)))
    })

result = MySchema().load(d)
```

But i keep getting
```Traceback (most recent call last):
  File "validate.py", line 33, in <module>
    result = MySchema().load(d)
  File "/home/user/test/bash/testing/env/lib/python3.5/site-packages/marshmallow/schema.py", line 690, in load
    data, many=many, partial=partial, unknown=unknown, postprocess=True
  File "/home/user/test/bash/testing/env/lib/python3.5/site-packages/marshmallow/schema.py", line 852, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'srv': ['Unknown field.']}
```

**Comment by sloria** [comment]
The idea is that you would dynamically build the dictionary passed to `from_dict`, such that it would include `srv` when appropriate.

**Comment by keith6014** [comment]
i see. I need to do
```python
s=MySchema().from_dict(d)
```

But how can I run validation against it?

**Comment by sloria** [comment]
`from_dict` returns a schema class, so you would instantiate and call `validate` or `load`, as normal

```python
ItemSchema = Schema.from_dict(...)
ItemSchema().load(data)
```

**Comment by keith6014** [comment]
Yeah, I am trying that that doesn't seem to work.

```python

class HostSchema(Schema):
    host = fields.Str()

ItemSchema = Schema.from_dict({
    "title" : fields.Str(),
    "unknown_key": fields.Dict(keys=fields.Str(),values=fields.List(fields.Nested(HostSchema)))
    })

result = ItemSchema().load(d)
```
Error
```
marshmallow.exceptions.ValidationError: {'srv': ['Unknown field.']}
```

**Comment by sloria** [comment]
What isn't working? Can you post a code snippet?

**Comment by keith6014** [comment]
```python
import sys,json,toml
from marshmallow import Schema, fields, post_load,ValidationError
from marshmallow import Schema as BaseSchema

class Schema(BaseSchema):
    @classmethod
    def from_dict(cls, fields_dict):
        attrs = fields_dict.copy()
        attrs["Meta"] = type(
                "GeneratedMeta", (getattr(cls, "Meta", object),), {"register": False}
                )
        return type("", (cls,), attrs)

class HostSchema(Schema):
    host = fields.Str()

ItemSchema = Schema.from_dict({
    "title" : fields.Str(),
    "unknown_key": fields.Dict(keys=fields.Str(),values=fields.Dict(keys=fields.Str(),values=fields.List(fields.Nested(HostSchema))))
    })

d=toml.load("fs/static.toml")
print (json.dumps(d,indent=2))
result = ItemSchema().load(d)
```

Here is the source
```toml
title = "arba"

[[srv.A]]
"server:export0" = "/mp1"
"server:export1" = "/mp2"

[[srv.B]]
"server:export1" = "/mnt/ffee"

[[srv.C]]
"server:export2" = "/mnt/ffee"
```

**Comment by lafrech** [comment]
IIUC, the field name is unknown at schema instantiation time.

Could be a case for https://github.com/marshmallow-code/marshmallow/issues/853.

**Comment by sloria** [comment]
@keith6014  You need to build the schema based on the data in the file.

```python
from pprint import pprint

import toml
from marshmallow import Schema, fields, ValidationError


d = toml.load("static.toml")


def is_valid_server_key(value):
    if not value.startswith("server:export"):
        raise ValidationError('Server key must start with "server:export')


schema_fields = {"title": fields.Str()}
if "srv" in d:
    schema_fields["srv"] = fields.Dict(
        fields.Str(),
        fields.List(
            fields.Dict(fields.Str(validate=is_valid_server_key), fields.Str())
        ),
    )
ItemSchema = Schema.from_dict(schema_fields)

pprint(ItemSchema().load(d), indent=2)
```
