### ISSUE TITLE
validate.Equal() is not working

### ISSUE THREAD

**Issue by FCNealVillangca** [marshmallow-code/marshmallow#1509]
confirm_password = fields.String(validate=validate.Equal(comparable=password))

the validation is not disappearing even if the password and confirm password is the same

**Comment by deckar01** [comment]
```py
>>> class Test(Schema):
...   password = fields.String()
...   confirm_password = fields.String(validate=validate.Equal(password))
... 
>>> Test().load({'password': 'secret', 'confirm_password': 'secret'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 723, in load
    data, many=many, partial=partial, unknown=unknown, postprocess=True
  File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 904, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'confirm_password': ["Must be equal to <fields.String(...)>."]}
```

`password` references a field instance in this context. Use schema-level validation to validate a relationship between two fields.

https://marshmallow.readthedocs.io/en/stable/extending.html#schema-level-validation
