### ISSUE TITLE
Serializing ObjectId

### ISSUE THREAD

**Issue by mekanix** [marshmallow-code/marshmallow#1542]
When trying to serialize MongoEngine object the following error is raised
```
Traceback (most recent call last):
  File "/usr/home/devel/.virtualenvs/freenitback/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/home/devel/.virtualenvs/freenitback/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/home/devel/.virtualenvs/freenitback/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/home/devel/.virtualenvs/freenitback/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/home/devel/.virtualenvs/freenitback/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/home/devel/.virtualenvs/freenitback/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/home/devel/.virtualenvs/freenitback/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/home/devel/.virtualenvs/freenitback/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/home/devel/.virtualenvs/freenitback/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/home/devel/.virtualenvs/freenitback/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/home/devel/.virtualenvs/freenitback/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/home/devel/.virtualenvs/freenitback/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/home/devel/.virtualenvs/freenitback/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/home/devel/.virtualenvs/freenitback/lib/python3.7/site-packages/flask/views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "/usr/home/devel/.virtualenvs/freenitback/lib/python3.7/site-packages/flask_smorest/response.py", line 80, in wrapper
    func(*args, **kwargs))
  File "/usr/home/devel/.virtualenvs/freenitback/lib/python3.7/site-packages/webargs/core.py", line 459, in wrapper
    return func(*new_args, **kwargs)
  File "/usr/home/devel/.virtualenvs/freenitback/lib/python3.7/site-packages/flask_smorest/arguments.py", line 77, in wrapper
    return func(*f_args, **f_kwargs)
  File "/usr/src/freenit/api/auth.py", line 52, in post
    access_token = create_access_token(identity=user.id)
  File "/usr/home/devel/.virtualenvs/freenitback/lib/python3.7/site-packages/flask_jwt_extended/utils.py", line 173, in create_access_token
    headers=headers)
  File "/usr/home/devel/.virtualenvs/freenitback/lib/python3.7/site-packages/flask_jwt_extended/jwt_manager.py", line 522, in _create_access_token
    headers=headers
  File "/usr/home/devel/.virtualenvs/freenitback/lib/python3.7/site-packages/flask_jwt_extended/tokens.py", line 77, in encode_access_token
    json_encoder=json_encoder, headers=headers)
  File "/usr/home/devel/.virtualenvs/freenitback/lib/python3.7/site-packages/flask_jwt_extended/tokens.py", line 30, in _encode_jwt
    json_encoder=json_encoder, headers=headers).decode('utf-8')
  File "/usr/home/devel/.virtualenvs/freenitback/lib/python3.7/site-packages/jwt/api_jwt.py", line 61, in encode
    cls=json_encoder
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/home/devel/.virtualenvs/freenitback/lib/python3.7/site-packages/flask_mongoengine/json.py", line 18, in default
    return superclass.default(self, obj)
  File "/usr/home/devel/.virtualenvs/freenitback/lib/python3.7/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
```

So, how to write a schema in this case? Or maybe better question is which field to use of ObjectId? I tried the type mapping suggested in https://stackoverflow.com/a/28094611 (first link while googling) but it doesn't work. Thank you!

**Comment by lafrech** [comment]
You need to define your own `ObjectId` field.

You may copy it from [umongo](https://github.com/Scille/umongo/blob/683decd58f8096ffb4a3a49df81db2f5115d0c60/umongo/marshmallow_bonus.py#L118-L132).

```py
class ObjectId(ma_fields.Field):
    """
    Marshmallow field for :class:`bson.ObjectId`
    """
    def _serialize(self, value, attr, obj):
        if value is None:
            return None
        return str(value)

    def _deserialize(self, value, attr, data):
        try:
            return bson.ObjectId(value)
        except (TypeError, bson.errors.InvalidId):
            raise ValidationError(_('Invalid ObjectId.'))
```

**Comment by mekanix** [comment]
Works like a charm. Thank you!
