### ISSUE TITLE
Dumping collections does not work with marshmallow 3.5.1 / Flask 1.1.1

### ISSUE THREAD

**Issue by embeddedc** [marshmallow-code/marshmallow#1550]
```
$ cat test.py 

from flask import Flask
from flask_marshmallow import Marshmallow
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)

db = SQLAlchemy(app)
ma = Marshmallow(app)

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)

class UserSchema(ma.Schema):
    class Meta:
        fields = ("id", "name")

user_schema = UserSchema()
users_schema = UserSchema(many=True)

@app.route("/api/users/")
def users():
    all_users = User.query.all()
    return users_schema.dump(all_users)


@app.route("/api/users/<id>")
def user_detail(id):
    user = User.query.get(id)
    return user_schema.dump(user)
```
`dump(user)`  works fine
```
$ curl localhost:5000/api/users/1

{
  "id": 1, 
  "name": "John"
}
```
`dump(all_users)` fails:
```
$ curl -L localhost:5000/api/user

[...]
Traceback (most recent call last):
  File "venv/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "venv/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "venv/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "venv/lib/python3.7/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "venv/lib/python3.7/site-packages/flask/app.py", line 2130, in make_response
    " {rv.__class__.__name__}.".format(rv=rv)
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a list.
```

**Comment by embeddedc** [comment]
```
$ pip freeze
Flask==1.1.1
flask-marshmallow==0.11.0
Flask-SQLAlchemy==2.4.1
marshmallow==3.5.1
marshmallow-sqlalchemy==0.22.3
SQLAlchemy==1.3.15
```

Similar issue has been filed for Flask: https://github.com/pallets/flask/issues/3348

**Comment by deckar01** [comment]
It's odd, but flask allows routes to return several types and lists aren't one of them.

https://flask.palletsprojects.com/en/1.1.x/quickstart/#about-responses

Flask provides `jsonify()`, which does basically the same thing as `schema.dumps()` would, but also wraps it in a response object with the mimetype set to JSON. You can pass a list to this method, and it is the pattern I see used the most often.

https://flask.palletsprojects.com/en/1.1.x/api/#flask.json.jsonify

**Comment by jimmy-lt** [comment]
Well, I'm actually debugging an issue of the same kind, Marshmallow 3.5.1 and Pyramid. It seems the following piece of code is causing the issue:

https://github.com/marshmallow-code/marshmallow/blob/685357d78bf34274b71ad8177af21e3d158c9ccf/src/marshmallow/schema.py#L545-L547

Before, `obj` is a dictionary and `many` is `True`. After, `obj` is a list of the keys from the dictionary.

Changing above code to:

```py
many = self.many if many is None else bool(many) 
if many and is_iterable_but_not_string(obj): 
    obj = [obj, ] 
```

Provides better results.

**Comment by deckar01** [comment]
@spack971 That appears to be unrelated. Can you open a separate issue?

**Comment by jimmy-lt** [comment]
@deckar01 Indeed, the bug I'm talking about was caused by my own code.
