### ISSUE TITLE
Nested List of a base schema to deserialize subclasses (using marshmallow-dataclass)

### ISSUE THREAD

**Issue by den4uk** [marshmallow-code/marshmallow#1705]
I have a rather unique case over here, which may not be an issue with the framework, but rather how can I hack the framework in order to fit the requirements.

I am using `marshmallow-dataclass` in my implementation, however, the issue arises from the `marshmallow` core. I believe the behaviour would be identical if I didn't use `marshmallow-dataclass`.

**The Problem**
> *The example used is a simplified version of the code*

In short, I have a base schema model (`Base`), which is subclassed by other schemas (`NameAge` and `NameLocation`).
I have another schema (`Store`) holding a list of the subclassed instances. The role of the store is collecting subclassed instanced, serializing and deserializing the lot as one.
I don't have issues serializing the instances of the `Store` to JSON, however, when deserializing it back, the schema model for deserialization used to deserialize `.items` is the base schema model (`Base`) instead of using the schema it was serialized with.

**Attempts so far**
As you can see in the example, I create a `BaseSchema`, which is used with the `Base`. I utilise decorators to add `_klass` value to the dump payloads, which works. I then try fetching the value out when deserializing, fetching the right model, and try overwriting the `self` instance with the new model. In theory, the approach works on a debugger - the data gets loaded as an intended class. But the `self` instance does not get modified, and the initial schema instance `BaseSchema` is used, thus throwing the error. This is obvious which schema was used for deserialization as an instance cannot be initialised without an overwritten abstract class method.

```python
import marshmallow
from abc import ABC, abstractmethod
from typing import List
import marshmallow_dataclass


class BaseSchema(marshmallow.Schema):
    @property
    def _model(self):
        return Base

    @marshmallow.pre_dump
    def _get_klass(self, obj, **kwargs):
        obj._klass = obj.__class__.__name__

    @marshmallow.post_dump(pass_original=True)
    def _return_subclass_dict(self, data, obj, **kwargs):
        schema = obj.Schema(**kwargs)
        return schema.dump(obj)

    @marshmallow.pre_load
    def _patch_self(self, data, **kwargs):
        if data.get('_klass'):
            model = self._model._get_klass(data['_klass'])
            schema = model.Schema(**kwargs)
            # This in theory should work, but does not behave as intended
            self.__class__ = schema.__class__
            self.__dict__.update(schema.__dict__)
        return data


@marshmallow_dataclass.dataclass(base_schema=BaseSchema)
class Base(ABC):
    name: str
    _klass: str = None

    @abstractmethod
    def some_abc_method(self):
        raise NotImplementedError

    @classmethod
    def _get_klass(cls, klass_name) -> type:
        klasses = {k.__name__: k for k in cls.__subclasses__()}
        return klasses[klass_name]


@marshmallow_dataclass.dataclass
class NameAge(Base):
    age: int = None

    def some_abc_method(self):
        pass


@marshmallow_dataclass.dataclass
class NameLocation(Base):
    location: str = None

    def some_abc_method(self):
        pass


@marshmallow_dataclass.dataclass
class Store:
    items: List[Base]


# Usage
a1 = NameAge(name='John', age=33)
# NameAge(name='John', _klass='NameAge', age=33)
a2 = NameLocation(name='Bob', location='Brighton')
# NameLocation(name='Bob', _klass='NameLocation', location='Brighton')

store = Store(items=[a1, a2])
# Store(items=[NameAge(name='John', _klass='NameAge', age=33), NameLocation(name='Bob', _klass='NameLocation', location='Brighton')])

payload = Store.Schema().dump(store)
# {'items': [{'_klass': 'NameAge', 'age': 33, 'name': 'John'}, {'_klass': 'NameLocation', 'location': 'Brighton', 'name': 'Bob'}]}

store_again = Store.Schema().load(payload)
# TypeError: Can't instantiate abstract class Base with abstract methods some_abc_method

# # Desired outcome
# assert store == store_again
```

Full traceback when the TypeError is raised:

```
Traceback (most recent call last):
  File "test.py", line 80, in <module>
    store_again = Store.Schema().load(payload)
  File "/Users/denis/.py38/lib/python3.8/site-packages/marshmallow_dataclass/__init__.py", line 563, in load
    all_loaded = super().load(data, many=many, **kwargs)
  File "/Users/denis/.py38/lib/python3.8/site-packages/marshmallow/schema.py", line 727, in load
    return self._do_load(
  File "/Users/denis/.py38/lib/python3.8/site-packages/marshmallow/schema.py", line 861, in _do_load
    result = self._deserialize(
  File "/Users/denis/.py38/lib/python3.8/site-packages/marshmallow/schema.py", line 669, in _deserialize
    value = self._call_and_store(
  File "/Users/denis/.py38/lib/python3.8/site-packages/marshmallow/schema.py", line 496, in _call_and_store
    value = getter_func(data)
  File "/Users/denis/.py38/lib/python3.8/site-packages/marshmallow/schema.py", line 666, in <lambda>
    getter = lambda val: field_obj.deserialize(
  File "/Users/denis/.py38/lib/python3.8/site-packages/marshmallow/fields.py", line 346, in deserialize
    output = self._deserialize(value, attr, data, **kwargs)
  File "/Users/denis/.py38/lib/python3.8/site-packages/marshmallow/fields.py", line 718, in _deserialize
    result.append(self.inner.deserialize(each, **kwargs))
  File "/Users/denis/.py38/lib/python3.8/site-packages/marshmallow/fields.py", line 346, in deserialize
    output = self._deserialize(value, attr, data, **kwargs)
  File "/Users/denis/.py38/lib/python3.8/site-packages/marshmallow/fields.py", line 601, in _deserialize
    return self._load(value, data, partial=partial)
  File "/Users/denis/.py38/lib/python3.8/site-packages/marshmallow/fields.py", line 584, in _load
    valid_data = self.schema.load(value, unknown=self.unknown, partial=partial)
  File "/Users/denis/.py38/lib/python3.8/site-packages/marshmallow_dataclass/__init__.py", line 568, in load
    return clazz(**all_loaded)
TypeError: Can't instantiate abstract class Base with abstract methods some_abc_method
```

I would much appreciate suggestions on making this work.

Thank you.

**Comment by sloria** [comment]
@den4uk Have you taken a look at [marshmallow-oneofschema](https://github.com/marshmallow-code/marshmallow-oneofschema)? It allows you to define polymorphic schemas, which looks like what you're trying to achieve.

**Comment by den4uk** [comment]
Hi Steven, many thanks for the suggestion!

I tried [marshmallow-oneofschema](https://github.com/marshmallow-code/marshmallow-oneofschema) as suggested, but it didn't work nicely with the `marshmallow-dataclass`. However, having digged in the issues, I found a solution which worked much nicer instead. Here my final (for the record):

```python
import marshmallow
import marshmallow_dataclass
from dataclasses import field
from abc import ABC, abstractmethod
from typing import List, Union


class BaseSchema(marshmallow.Schema):
    @marshmallow.pre_dump
    def _get_klass(self, obj, **kwargs):
        obj._klass = obj.__class__.__name__
        return obj


@marshmallow_dataclass.dataclass
class Base(ABC):
    name: str
    _klass: str = field(default=None, repr=False)

    @abstractmethod
    def some_abc_method(self):
        raise NotImplementedError


@marshmallow_dataclass.dataclass(base_schema=BaseSchema)
class NameAge(Base):
    age: int = None

    def some_abc_method(self):
        pass


@marshmallow_dataclass.dataclass(base_schema=BaseSchema)
class NameLocation(Base):
    location: str = None

    def some_abc_method(self):
        pass


@marshmallow_dataclass.dataclass
class Store:
    items: List[Union[
        NameAge,
        NameLocation
    ]] = field(default_factory=list)


# Usage
a1 = NameAge(name='John', age=33)
# NameAge(name='John', _klass='NameAge', age=33)
a2 = NameLocation(name='Bob', location='Brighton')
# NameLocation(name='Bob', _klass='NameLocation', location='Brighton')

store = Store(items=[a1, a2])
# Store(items=[NameAge(name='John', _klass='NameAge', age=33), NameLocation(name='Bob', _klass='NameLocation', location='Brighton')])

payload = Store.Schema().dump(store)
# {'items': [{'_klass': 'NameAge', 'age': 33, 'name': 'John'}, {'_klass': 'NameLocation', 'location': 'Brighton', 'name': 'Bob'}]}

store_again = Store.Schema().load(payload)

# Desired outcome
assert store == store_again
```
Many thanks for the help!
