### ISSUE TITLE
Does dotted notation for `only` and `exclude` work with list of nested schemas?

### ISSUE THREAD

**Issue by varunbpatil** [marshmallow-code/marshmallow#1886]
```python
from marshmallow import Schema, fields


class BookSchema(Schema):
    id = fields.Int(dump_only=True)
    title = fields.Str()


class AuthorSchema(Schema):
    id = fields.Int(dump_only=True)
    title = fields.Str()
    books = fields.List(fields.Nested(BookSchema()))

class LibrarySchema(Schema):
    authors = fields.List(fields.Nested(AuthorSchema()))


res = LibrarySchema(exclude=("authors.books.id",)).dump(
    {
        "authors": [
            {
                "id": 1,
                "title": "my_fav_author",
                "books": [
                    { "id": 1, "title": "book_1" },
                    { "id": 2, "title": "book_2" }
                ]
            }
        ]
    }
)
```

gives the following exception.

```
Traceback (most recent call last):
  File "test2.py", line 18, in <module>
    res = LibrarySchema(exclude=("authors.books.id",)).dump(
  File "/home/varun/.cache/pypoetry/virtualenvs/feast-ntQX6VRz-py3.8/lib/python3.8/site-packages/marshmallow/schema.py", line 552, in dump
    result = self._serialize(processed_obj, many=many)
  File "/home/varun/.cache/pypoetry/virtualenvs/feast-ntQX6VRz-py3.8/lib/python3.8/site-packages/marshmallow/schema.py", line 520, in _serialize
    value = field_obj.serialize(attr_name, obj, accessor=self.get_attribute)
  File "/home/varun/.cache/pypoetry/virtualenvs/feast-ntQX6VRz-py3.8/lib/python3.8/site-packages/marshmallow/fields.py", line 338, in serialize
    return self._serialize(value, attr, obj, **kwargs)
  File "/home/varun/.cache/pypoetry/virtualenvs/feast-ntQX6VRz-py3.8/lib/python3.8/site-packages/marshmallow/fields.py", line 757, in _serialize
    return [self.inner._serialize(each, attr, obj, **kwargs) for each in value]
  File "/home/varun/.cache/pypoetry/virtualenvs/feast-ntQX6VRz-py3.8/lib/python3.8/site-packages/marshmallow/fields.py", line 757, in <listcomp>
    return [self.inner._serialize(each, attr, obj, **kwargs) for each in value]
  File "/home/varun/.cache/pypoetry/virtualenvs/feast-ntQX6VRz-py3.8/lib/python3.8/site-packages/marshmallow/fields.py", line 620, in _serialize
    schema = self.schema
  File "/home/varun/.cache/pypoetry/virtualenvs/feast-ntQX6VRz-py3.8/lib/python3.8/site-packages/marshmallow/fields.py", line 586, in schema
    self._schema._init_fields()
  File "/home/varun/.cache/pypoetry/virtualenvs/feast-ntQX6VRz-py3.8/lib/python3.8/site-packages/marshmallow/schema.py", line 971, in _init_fields
    raise ValueError(message)
ValueError: Invalid fields for <AuthorSchema(many=False)>: {'books.id'}.

```

**Comment by varunbpatil** [comment]
Found the issue. My schema was incorrect.

Needed to replace this
```
books = fields.List(fields.Nested(BookSchema()))
authors = fields.List(fields.Nested(AuthorSchema()))
```
with this
```
books = fields.List(fields.Nested(BookSchema))
authors = fields.List(fields.Nested(AuthorSchema))

```

**Comment by deckar01** [comment]
I don't think classes are supposed to produce a different behavior than instances. I suspect that is a bug. I am going to reopen this to see if I can get dotted attribute access to work with instances. Thank you for reporting this.

**Comment by deckar01** [comment]
Nevermind, this is documented behavior.

https://marshmallow.readthedocs.io/en/stable/marshmallow.fields.html?highlight=exclude#marshmallow.fields.Nested

> When passing a Schema instance as the first argument, the instance’s exclude, only, and many attributes will be respected.
> 
> Therefore, when passing the exclude, only, or many arguments to fields.Nested, you should pass a Schema class (not an instance) as the first argument.

**Comment by lafrech** [comment]
Still this is surprising and maybe something we might want to address in a future refactor that would allow changing schema parameters after init.
