### ISSUE TITLE
Dict data validated as fields.List: passes and silently drops data

### ISSUE THREAD

**Issue by andrewbaxter** [marshmallow-code/marshmallow#189]
Here's the code I tested with:

``` python2
import collections

from marshmallow import Schema, fields, pprint

class ListInnerSchema(Schema):
    y = fields.Int()

class TestSchema(Schema):
    x = fields.List(fields.Nested(ListInnerSchema()))

schema = TestSchema()
begin = {'x': {'a': 'b'}}
end = schema.dump(begin)
print('begin: {}'.format(begin))
print('end: {}'.format(end))
```

Here's the output:

``` python2
begin: {'x': {'a': 'b'}}
end: MarshalResult(data={u'x': [{u'y': 0}]}, errors={})
```

I didn't intend to dump a dict, but I had some bad data and it passed with no errors.

**Comment by andrewbaxter** [comment]
I think this is related to #45 - will comment there.

**Comment by andrewbaxter** [comment]
As per discussion in #45 I tried it with an explicit validate on dump.

###### With a list of nested:

``` python
from marshmallow import Schema, fields, pprint

class ListInnerSchema(Schema):
    y = fields.Int()

class TestSchema(Schema):
    x = fields.List(fields.Nested(ListInnerSchema), required=True)

schema = TestSchema()
begin = {'x': {'y1': 14}}
print('errors: {}'.format(schema.validate(begin)))
end = schema.dump(begin)
print('begin: {}'.format(begin))
print('end: {}'.format(end))
```

Output:

```
errors: {}
begin: {'x': {'y1': 14}}
end: MarshalResult(data={u'x': [{u'y': 0}]}, errors={})
```

###### With nested many=True:

``` python
from marshmallow import Schema, fields, pprint

class ListInnerSchema(Schema):
    y = fields.Int()

class TestSchema(Schema):
    x = fields.Nested(ListInnerSchema, many=True)

schema = TestSchema()
begin = {'x': {'y1': 14}}
print('errors: {}'.format(schema.validate(begin)))
end = schema.dump(begin)
print('begin: {}'.format(begin))
print('end: {}'.format(end))
```

Output:

```
Traceback (most recent call last):
  File "a.py", line 11, in <module>
    print('errors: {}'.format(schema.validate(begin)))
  File "/.../marshmallow/schema.py", line 529, in validate
    _, errors = self._do_load(data, many, postprocess=False)
  File "/.../marshmallow/schema.py", line 606, in _do_load
    dict_class=self.dict_class
  File "/.../marshmallow/fields.py", line 295, in deserialize
    strict=strict
  File "/.../marshmallow/fields.py", line 107, in _call_and_store
    value = getter_func(data)
  File "/.../marshmallow/fields.py", line 468, in deserialize
    return self._call_and_reraise(do_deserialization, UnmarshallingError)
  File "/.../marshmallow/fields.py", line 418, in _call_and_reraise
    return func()
  File "/.../marshmallow/fields.py", line 465, in do_deserialization
    output = self._deserialize(value)
  File "/.../marshmallow/fields.py", line 604, in _deserialize
    data, errors = self.schema.load(value)
  File "/.../marshmallow/schema.py", line 500, in load
    result, errors = self._do_load(data, many, postprocess=True)
  File "/.../marshmallow/schema.py", line 606, in _do_load
    dict_class=self.dict_class
  File "/.../marshmallow/fields.py", line 276, in deserialize
    for d in data]
  File "/.../marshmallow/fields.py", line 285, in deserialize
    raw_value = data.get(attr_name, missing)
AttributeError: 'str' object has no attribute 'get'
```

I would expect an error to be returned from validate (and no exception thrown in any case).

**Comment by sloria** [comment]
I believe this is the same as #188 . A nested list is expected to be passed; non-list values are not being handled gracefully. Closing this for now; further discussion should continue on #188
