### ISSUE TITLE
AttributeError on deserialization of flat Nested field

### ISSUE THREAD

**Issue by m1kola** [marshmallow-code/marshmallow#194]
According [documentation](http://marshmallow.readthedocs.org/en/latest/nesting.html#specifying-which-fields-to-nest) we can create flat `Nested` fields with code like this:

``` Python
from marshmallow import fields, Schema


class SchemaFoo(Schema):
    id = fields.Integer()


class SchemaBar(Schema):
    foos = fields.Nested(SchemaFoo, only='id', many=True)

bar_schema = SchemaBar()
```

`dump` works fine:

```
>>> bar_schema.dump({"foos": [{"id": 1}, {"id": 2}]})
MarshalResult(data={u'foos': [1, 2]}, errors={})
```

But `load` fails:

```
bar_schema.loads(bar_schema.dumps({"foos": [{"id": 1}, {"id": 2}]}).data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/m1kola/.virtualenvs/pts/lib/python2.7/site-packages/marshmallow/schema.py", line 515, in loads
    return self.load(data, many=many)
  File "/Users/m1kola/.virtualenvs/pts/lib/python2.7/site-packages/marshmallow/schema.py", line 500, in load
    result, errors = self._do_load(data, many, postprocess=True)
  File "/Users/m1kola/.virtualenvs/pts/lib/python2.7/site-packages/marshmallow/schema.py", line 606, in _do_load
    dict_class=self.dict_class
  File "/Users/m1kola/.virtualenvs/pts/lib/python2.7/site-packages/marshmallow/fields.py", line 295, in deserialize
    strict=strict
  File "/Users/m1kola/.virtualenvs/pts/lib/python2.7/site-packages/marshmallow/fields.py", line 107, in _call_and_store
    value = getter_func(data)
  File "/Users/m1kola/.virtualenvs/pts/lib/python2.7/site-packages/marshmallow/fields.py", line 468, in deserialize
    return self._call_and_reraise(do_deserialization, UnmarshallingError)
  File "/Users/m1kola/.virtualenvs/pts/lib/python2.7/site-packages/marshmallow/fields.py", line 418, in _call_and_reraise
    return func()
  File "/Users/m1kola/.virtualenvs/pts/lib/python2.7/site-packages/marshmallow/fields.py", line 465, in do_deserialization
    output = self._deserialize(value)
  File "/Users/m1kola/.virtualenvs/pts/lib/python2.7/site-packages/marshmallow/fields.py", line 604, in _deserialize
    data, errors = self.schema.load(value)
  File "/Users/m1kola/.virtualenvs/pts/lib/python2.7/site-packages/marshmallow/schema.py", line 500, in load
    result, errors = self._do_load(data, many, postprocess=True)
  File "/Users/m1kola/.virtualenvs/pts/lib/python2.7/site-packages/marshmallow/schema.py", line 606, in _do_load
    dict_class=self.dict_class
  File "/Users/m1kola/.virtualenvs/pts/lib/python2.7/site-packages/marshmallow/fields.py", line 276, in deserialize
    for d in data]
  File "/Users/m1kola/.virtualenvs/pts/lib/python2.7/site-packages/marshmallow/fields.py", line 285, in deserialize
    raw_value = data.get(attr_name, missing)
AttributeError: 'int' object has no attribute 'get'
```

Another case of deserialization works:

```
>>> bar_schema.load({"foos": [{"id": 1}, {"id": 2}]})
UnmarshalResult(data={'foos': [{'id': 1}, {'id': 2}]}, errors={})
```

But we can't process structure that has been serialized with `dump` method. It's sad :(

**Version:** 1.2.4. Same behaviour in dev branch, but with little bit different trace.

**Comment by m1kola** [comment]
#188 is similar issue, but about validation of non flat `Nested` fields. I think if we can `dump` to this:

```
{u'foos': [1, 2]}
```

we should have possibility to `load` this back.

**Comment by sloria** [comment]
@m1kola Indeed, when passing a string to `only`, it affects serialization but not deserialization. This is because the Schema does not know how to deserialize back to the full nested objects.

You might be able to get away with a processing the deserialized object in the `make_object` hook. If we go with the proposal in https://github.com/marshmallow-code/marshmallow/issues/153#issuecomment-90361036 , I think it will be easier.

**Comment by sloria** [comment]
@m1kola Update: If you are dealing with primary keys and ORM objects, you might want to take a look at `fields.QuerySelect` and `fields.QuerySelectList`.

**Comment by sloria** [comment]
Closing this for now.

I recommend looking at the `Relationship` field from marshmallow-sqlalchemy https://github.com/marshmallow-code/marshmallow-sqlalchemy/blob/dev/marshmallow_sqlalchemy/fields.py#L18) for this use case and adapting it for your needs.
