### ISSUE TITLE
`fields.Url` does not accept `file` URLs without host

### ISSUE THREAD

**Issue by 0xDEC0DE** [marshmallow-code/marshmallow#2249]
# Steps to reproduce

Run this test case:
```
import marshmallow as mm
class LOL(mm.Schema):
    url = mm.fields.Url(schemes={'file'})

LOL().load(dict(url="file:///var/storage/somefile.zip"))
```

# Expected result
```
{'url': 'file:///var/storage/somefile.zip'}
```

# Actual behavior
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nisimond/work/blastarea/lolwut/lib/python3.11/site-packages/marshmallow/schema.py", line 756, in loads
    return self.load(data, many=many, partial=partial, unknown=unknown)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nisimond/work/blastarea/lolwut/lib/python3.11/site-packages/marshmallow/schema.py", line 722, in load
    return self._do_load(
           ^^^^^^^^^^^^^^
  File "/Users/nisimond/work/blastarea/lolwut/lib/python3.11/site-packages/marshmallow/schema.py", line 909, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'url': ['Not a valid URL.']}
```

# Workaround

This works:
```
LOL().load(dict(url="file://localhost/var/storage/somefile.zip"))
```
...but the `hostname` portion is entirely optional with `file` URLs.

**Comment by sloria** [comment]
sorry for the delay. i was able to repro the issue. will investigate when i have some time. PRs welcome in the meantime
