### ISSUE TITLE
marshmallow==2.0.0b5   , pre_dump issues

### ISSUE THREAD

**Issue by Dowwie** [marshmallow-code/marshmallow#265]
When running this example application, an exception is raised.  It seems that the data argument of the pre_dump decorated method isn't interpreted as it should be?

source:  http://paste.ofcode.org/36RCsEeLxCCrEQvjvbgR2fM

Traceback (most recent call last):
  File "bug_marshmallow_v2beta.py", line 39, in <module>
    result = ris.dump(testdict).data
  File "/usr/local/lib/python3.4/dist-packages/marshmallow/schema.py", line 516, in dump
    obj = self._invoke_dump_processors(PRE_DUMP, obj, many)
  File "/usr/local/lib/python3.4/dist-packages/marshmallow/schema.py", line 759, in _invoke_dump_processors
    data = self._invoke_processors(tag_name, raw=False, data=data, many=many)
  File "/usr/local/lib/python3.4/dist-packages/marshmallow/schema.py", line 838, in _invoke_processors
    data = utils.if_none(processor(data), data)
  File "bug_marshmallow_v2beta.py", line 30, in process_realms
    data.get('realms').items()}
AttributeError: 'SimpleRealmIdentifierCollection' object has no attribute 'get'

**Comment by sloria** [comment]
`pre_dump` methods take the _object to be serialized_ as input--in your paste, that's an `SimpleRealmIdentifierCollection` object.

`post_dump` takes the serialized data as input. Changing the decorator to `post_dump` should fix your problem.

Edit: fix typo

**Comment by Dowwie** [comment]
thanks for clarifying!

changing to post_dump indeed does fix the issue
