### ISSUE TITLE
Error using "only" parameter with tuple in Serializer.__init__

### ISSUE THREAD

**Issue by milesrichardson** [marshmallow-code/marshmallow#27]
You have an error which seems to be the result of accidentally iterating over a string as if it were an array. Here is the code to produce the error:

```
from marshmallow import Serializer
from marshmallow import fields


class UserInputSerializer(Serializer):
    email = fields.String()
    username = fields.String()


json = {"email": "blah"}

user = UserInputSerializer(json, only=('email'))
```

Error generated:

```
> Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "<string>", line 12, in <module>
  File "/Users/miles/.../marshmallow/serializer.py", line 193, in __init__
    self._update_fields(obj)
  File "/Users/miles/.../marshmallow/serializer.py", line 294, in _update_fields
    ret = self.__filter_fields(self.only)
  File "/Users/miles/.../marshmallow/serializer.py", line 362, in __filter_fields
    '"{0}" is not a valid field for {1}.'.format(key, self.obj))
AttributeError: "e" is not a valid field for {'email': 'blah'}.
```

For diagnostic purposes, consider the following code (it shouldn't run -- but it should give a different error). If I change the name of the "email" field to "e", like so:

```
from marshmallow import Serializer
from marshmallow import fields


class UserInputSerializer(Serializer):
    e = fields.String()
    username = fields.String()


json = {"email": "blah"}

user = UserInputSerializer(json, only=('email'))
```

... and run this script, I get a similar error (notice the difference is "m" not "e"):

```
>>> Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "<string>", line 12, in <module>
  File "/Users/miles/.../marshmallow/serializer.py", line 193, in __init__
    self._update_fields(obj)
  File "/Users/miles/.../marshmallow/serializer.py", line 294, in _update_fields
    ret = self.__filter_fields(self.only)
  File "/Users/miles/.../marshmallow/serializer.py", line 362, in __filter_fields
    '"{0}" is not a valid field for {1}.'.format(key, self.obj))
AttributeError: "m" is not a valid field for {'email': 'blah'}.
```

If I change the field name to simply "e", and pass `only=('email')` , the code does not generate an error:

from marshmallow import Serializer
    from marshmallow import fields

```
class UserInputSerializer(Serializer):
    e = fields.String()
    username = fields.String()


json = {"e": "blah"}

user = UserInputSerializer(json, only=('e'))
```

(No error)

The good news is, it seems like the problem is only with tuples. The following code, using a list for the parameter, executes with no errors:

```
from marshmallow import Serializer
from marshmallow import fields


class UserInputSerializer(Serializer):
    email = fields.String()
    username = fields.String()


json = {"email": "blah"}

user = UserInputSerializer(json, only=['email'])
```

Ths problem appears to be in the __filter_fields function of Serializer.py. 

Please let me know if this is expected behavior and I'm doing something wrong...

**Comment by sloria** [comment]
The problem is that your are passing a string to the `only` parameter--not a tuple. 

In Python, one element tuples must have a common after the first element; otherwise Python interprets the expression as a string.

Here is the correction to your code example:

``` python
from marshmallow import Serializer
from marshmallow import fields


class UserInputSerializer(Serializer):
    email = fields.String()
    username = fields.String()


json = {"email": "blah"}

user = UserInputSerializer(json, only=('email', ))  # Note the comma
```

**Comment by milesrichardson** [comment]
Did not know that. Thanks.
