### ISSUE TITLE
python setup.py test is broken with setuptools>=18.4

### ISSUE THREAD

**Issue by nelfin** [marshmallow-code/marshmallow#300]
`setuptools.command.test.test_args` was changed to a read-only property in https://bitbucket.org/pypa/setuptools/commits/cf565b66b855dd4df189b679206f9fb113681737 so

``` python,name=setup.py
class PyTest(TestCommand):
    def finalize_options(self):
        TestCommand.finalize_options(self)
        self.test_args = ['--verbose', 'tests/']
```

fails with:

``` pytb
Traceback (most recent call last):
  File "setup.py", line 81, in <module>
    cmdclass={'test': PyTest},
  File "/opt/python/3.3.5/lib/python3.3/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/python/3.3.5/lib/python3.3/distutils/dist.py", line 930, in run_commands
    self.run_command(cmd)
  File "/opt/python/3.3.5/lib/python3.3/distutils/dist.py", line 948, in run_command
    cmd_obj.ensure_finalized()
  File "/opt/python/3.3.5/lib/python3.3/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "setup.py", line 15, in finalize_options
    self.test_args = ['--verbose', 'tests/']
AttributeError: can't set attribute
```

**Comment by sloria** [comment]
Thanks for investigating this. I think I'm going to just remove the pytest setup.py command; it is redundant. The preferred way to run the tests is `invoke test`.

**Comment by nelfin** [comment]
No worries, so you're thinking of changing `.travis.yml` to:

``` yaml
script: invoke test
```

then?

**Comment by sloria** [comment]
Correct: https://github.com/marshmallow-code/marshmallow/commit/1dbcae9c439d1a268717feb089351fc3c5180ac3
