### ISSUE TITLE
tests are failing with python-unittest2-1.1.0

### ISSUE THREAD

**Issue by xsuchy** [marshmallow-code/marshmallow#338]
When I have python-unittest2-0.8.0 tests pass all green. However when I use python-unittest2-1.1.0 (currently in Fedora rawhide) test fails with:

```
sh-4.3# python setup.py test
running test
running egg_info
writing requirements to marshmallow.egg-info/requires.txt
writing marshmallow.egg-info/PKG-INFO
writing top-level names to marshmallow.egg-info/top_level.txt
writing dependency_links to marshmallow.egg-info/dependency_links.txt
reading manifest file 'marshmallow.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*.pyc' found under directory 'docs'
warning: no previously-included files matching '*.pyo' found under directory 'docs'
warning: no previously-included files matching '*.pyo' found under directory 'tests'
warning: no previously-included files matching '*.pyc' found under directory 'examples'
warning: no previously-included files matching '*.pyo' found under directory 'examples'
no previously-included directories found matching 'docs/_build'
writing manifest file 'marshmallow.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 63, in <module>
    test_suite='tests'
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 153, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 134, in with_project_on_sys_path
    func()
  File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 174, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib64/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 37, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib64/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_options'
```

where the submodule variable have the value `tests.test_options`

**Comment by justanr** [comment]
Try installing and running with `tox`

```
pip install tox
tox
```

@sloria Should setup.py include an overriden test command to prevent this?

**Comment by xsuchy** [comment]
Surprisingly tox is not needed for test (at least - I do not have it on my workstation and tests are passing). I was missing simplejson. After adding it, that TB above disappeared and tests are passing.
