### ISSUE TITLE
ManyToMany DRF AttributeError: 'ListSerializer' object has no attribute '_update_fields'

### ISSUE THREAD

**Issue by anonymez** [marshmallow-code/marshmallow#986]
Hello everybody,

I'm migrating my web app from the standard DRF serialization to marshmallow.

I have the following models:

````
class Test(UserMixin):
    name = models.CharField(max_length=50)
    control = models.ForeignKey(Control,on_delete=models.PROTECT)
    testcase = JSONField()
    description = models.CharField(max_length=200,null=True, blank=True)
    result = models.NullBooleanField(null=True, blank=True)
    test_id = ArrayField(models.CharField(max_length=64,null=True),default=list,blank=True)
    target = models.ForeignKey(Target, on_delete=models.CASCADE)
    interval=models.ForeignKey(Interval,null=True,blank=True,on_delete=models.SET_NULL)

class UserEvaluationRule(UserMixin,TimestampsMixin):
    STATUSES = ((0, "FAIL",), (1, "SUCCESS",), (2, "PENDING"), )
    name = models.CharField("Name", max_length=50)
    description = models.TextField("Description", null=True, blank=True)
    aer = models.ForeignKey(AbstractEvaluationRule,default=None,blank=True,null=True,on_delete=models.SET_NULL,db_index=True)
    mapping = JSONField(default={})
    related_tests = models.ManyToManyField(Test, blank=True,db_index=True)
    related_ers = models.ManyToManyField("self", blank=True, null=True,symmetrical=False)
    result = models.NullBooleanField(null=True, blank=True)
    status_array= ArrayField(JSONField(),blank=True,null=True)
    status = models.IntegerField(choices=STATUSES, default=2)
    category = ArrayField(models.CharField('categories', blank=True,null=True,max_length=1024),null=True,blank=True)
    _formula = models.CharField("Formula", max_length=512,default=None,blank=True,null=True)
    test_formula = models.CharField("test_formula",max_length=512,blank=False,null=False)

````

I'm creating the Schemas for serializing UserEvaluationRule as follow:
````
class TestProvaSchema(Schema):
    id=fields.Int()
    name=fields.String()
    control_id=fields.Integer()
    target_id=fields.Int()
    dispatcher_id=fields.Int()
    testcase=fields.Raw()
    description=fields.String()
    result=fields.Boolean()

class SerialE(Schema):
    id=fields.Int()
    name = fields.String()
    description = fields.String()
    created_at = fields.DateTime()
    updated_at = fields.DateTime()
    category= fields.List(fields.Int)
    status=fields.Int()
    aer_id=fields.Int()
    test_formula=fields.String()
    related_tests= fields.Nested(TestSchema,many=True)
````

But i'm getting the following error:
````
[2018-10-10 17:04:27,184] ERROR    Internal Server Error: /evaluation-rulep/
Traceback (most recent call last):
  File "/Users/iridium/allMoonCloud/api/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/iridium/allMoonCloud/api/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/iridium/allMoonCloud/api/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/iridium/allMoonCloud/api/env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/iridium/allMoonCloud/api/env/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/iridium/allMoonCloud/api/env/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/iridium/allMoonCloud/api/env/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/iridium/allMoonCloud/api/env/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/iridium/allMoonCloud/api/env/lib/python3.6/site-packages/rest_framework/generics.py", line 201, in get
    return self.list(request, *args, **kwargs)
  File "/Users/iridium/allMoonCloud/api/api/evaluation_rules/views/EvaluationRulesList.py", line 88, in list
    data = serializer.data
  File "/Users/iridium/allMoonCloud/api/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 765, in data
    ret = super(ListSerializer, self).data
  File "/Users/iridium/allMoonCloud/api/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "/Users/iridium/allMoonCloud/api/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 683, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/Users/iridium/allMoonCloud/api/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 683, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/Users/iridium/allMoonCloud/api/env/lib/python3.6/site-packages/rest_marshmallow/__init__.py", line 34, in to_representation
    return self.dump(instance)
  File "/Users/iridium/allMoonCloud/api/env/lib/python3.6/site-packages/marshmallow/schema.py", line 454, in dump
    index_errors=self.opts.index_errors,
  File "/Users/iridium/allMoonCloud/api/env/lib/python3.6/site-packages/marshmallow/marshalling.py", line 148, in serialize
    index=(index if index_errors else None),
  File "/Users/iridium/allMoonCloud/api/env/lib/python3.6/site-packages/marshmallow/marshalling.py", line 79, in call_and_store
    value = getter_func(data)
  File "/Users/iridium/allMoonCloud/api/env/lib/python3.6/site-packages/marshmallow/marshalling.py", line 143, in <lambda>
    getter = lambda d: field_obj.serialize(attr_name, d, accessor=accessor)
  File "/Users/iridium/allMoonCloud/api/env/lib/python3.6/site-packages/marshmallow/fields.py", line 263, in serialize
    return self._serialize(value, attr, obj)
  File "/Users/iridium/allMoonCloud/api/env/lib/python3.6/site-packages/marshmallow/fields.py", line 456, in _serialize
    schema._update_fields(obj=nested_obj, many=self.many)
AttributeError: 'ListSerializer' object has no attribute '_update_fields'
[10/Oct/2018 17:04:27] "GET /evaluation-rulep/ HTTP/1.1" 500 20605
````

Just point out my libraries, i'm using:
````
Django==2.1.2
djangorestframework==3.8.2
django-rest-marshmallow==3.1.1
marshmallow==3.0.0b16



Python 3.6.3
````

**Comment by sloria** [comment]
@anonymez Would you try upgrading to marshmallow 3.0.0b18 and see if that resolves the issue?

**Comment by lafrech** [comment]
@anonymez, are you still interested in this, or shall we close the issue?

**Comment by sloria** [comment]
Closing for now. Feel free to comment if you're still having this issue.
